name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, macOS, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm test

  release:
    name: release
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event_name == 'push'
      && github.ref == 'refs/heads/master'
      && github.repository == 'probot/create-probot-app'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
